### ISSUE TITLE
Divide REQ-5 

### ISSUE THREAD

**Issue by dkile** [cau-sw-engineering-2021/online-pizza-ordering-system#11]
REQ-5를 보면 receiving option이 배달, 테이크아웃, 매장 식사가 있습니다. 이걸 online/offline을 축으로 분리를 시키는 게 나을까요?

**Comment by alertjjm** [comment]
용준님이랑 얘기해보면서 문제점을 인식해봤는데, online 주문상태확인은(배민처럼 주문접수, 조리중, 배달중 etc)이렇게 확인이 가능하고, offline주문상태확인은(맥날처럼 조리중, 수령가능)이렇게 확인이 가능해야하잖아요.
그런데, takeout같은경우는 주문상태확인을 맥날 offline매장처럼 확인을 해야되잖아요 그래서 이게 구분이 약간 애매해서 의견듣고싶습니다!

**Comment by alertjjm** [comment]
제생각은 on/offline구분을 주문당시로 구분하는게아니라 수령당시로 구분해서 개념정립을 online(배달만), offline(takeout, 직접매장식사)로 구분하는게 나을거같다고 생각을 했습니다. 어차피 주문 페이지는 달라질 것이 없어서 개념정립만 하면될거같다고 생각했습니다.

**Comment by identity16** [comment]
배달의 민족 사례를 살펴봤는데요.
'배민오더'라는 개념이 [테이블 주문(매장에 앉아서 모바일로 주문) + 테이크아웃 주문] 형식이라서
저희도 이 형식을 차용해서 @alertjjm 님 말씀대로 Online(배달) / Offline(테이크아웃, 매장식사)로 나누면 좋을 것 같습니다.

**Comment by jooomOut** [comment]
개인적인 생각으로는 현존하는 3가지 옵션으로도 문제가 없을 것 같고 on/off에 대한 추가적인 구분이 필요가 없다고 보여요.
이와 관련된 타 요구사항에서 시스템이 "어떠한" 고객에게 무엇을 보여준다고 적혀있는데 이것보다는
1. 온라인 시스템 상에서는 자신의 주문 내역에 대한 트래킹만 보여주기
2. 오프라인, 즉 매장안의 디스플레이에서는 포장과 매장 내 식사에 대한 모든 주문 내역을 보여주기
로 해결하는게 조금 더 나을 것 같습니당

**Comment by alertjjm** [comment]
Orderer를 제가 on/offline으로 어제 나눠서 커밋했었는데 제가 다시생각해보니까 @jooomOut 님 말처럼 Orderer를 on/offline으로 구분안해도될거같아요 Orderer는 그냥 Orderer로 놔두고

Display할때만 if(option=="delivery") , if(option=="for here" || "to go")로 해서 페이지를 나누는게 덜꼬일거같아요

**Comment by jooomOut** [comment]
> Orderer를 제가 on/offline으로 어제 나눠서 커밋했었는데 제가 다시생각해보니까 @jooomOut 님 말처럼 Orderer를 on/offline으로 구분안해도될거같아요 Orderer는 그냥 Orderer로 놔두고
> 
> Display할때만 if(option=="delivery") , if(option=="for here" || "to go")로 해서 페이지를 나누는게 덜꼬일거같아요

넴 글구 배달, 포장, 매장 내 식사 무엇을 고르더라도 온라인 시스템에서 주문한거니 현 진행 상황은 온라인으로 확인할 수 있어야 한다고 생각해요.

**Comment by alertjjm** [comment]
> > Orderer를 제가 on/offline으로 어제 나눠서 커밋했었는데 제가 다시생각해보니까 @jooomOut 님 말처럼 Orderer를 on/offline으로 구분안해도될거같아요 Orderer는 그냥 Orderer로 놔두고
> > Display할때만 if(option=="delivery") , if(option=="for here" || "to go")로 해서 페이지를 나누는게 덜꼬일거같아요
> 
> 넴 글구 배달, 포장, 매장 내 식사 무엇을 고르더라도 온라인 시스템에서 주문한거니 현 진행 상황은 온라인으로 확인할 수 있어야 한다고 생각해요.

넵넵넵 맥도날드처럼 보여주는 simplepage도 어차피 웹페이지로 만들어놓고 오프라인 매장에서 TV로만 띄워서 보여주는거기때문에 무엇을고르더라도 온라인으로 확인할 수 있게할거같습니다.

**Comment by dkile** [comment]
정리가 된 것 같으니 이 이슈는 이제 닫겠습니다. 도움 주셔서 감사합니다.
