### ISSUE TITLE
Fix some requirements

### ISSUE THREAD

**Issue by jooomOut** [cau-sw-engineering-2021/online-pizza-ordering-system#12]
REQ-9-4 - "The system shall change the order status to "invalid" in an emergency" 는 NF가 아니고 F인 것 같고
마지막 TODO의 "The system shall not accept orders outside of the opening hours"는 NF인 것 같습니다.

고치려다가 일단 다른 분들 의견 여쭤보는게 나을 것 같아서 올립니당.

**Comment by alertjjm** [comment]
제 생각도 같습니다.

**Comment by makerdark98** [comment]
좋습니다.

**Comment by identity16** [comment]
동의합니다🙂

**Comment by jooomOut** [comment]
이슈 닫고 고치겠습니당
