### ISSUE TITLE
Requirement에 대한 건의

### ISSUE THREAD

**Issue by sikutisa** [cau-sw-engineering-2021/online-pizza-ordering-system#13]
Reqirement에 Identifier가 지정되지 않은 항목들이 있는데, 차후 usecase에 대한 Schema 작성을 위해서라도 Identifier를 만드는 것이 좋지 않을까 생각합니다. 추가로,
`| | TODO | The system shall maintain a history log of all orders. | NF |`
에서 말하는 history log가 orderer를 위한 것인지, 가게를 위한 것인지, 양쪽 모두를 위한 것인지 궁금합니다.

**Comment by makerdark98** [comment]
질문 1
Requirement는 거의 다 나온것 같은데, Identifier를 다 추가해놓겠습니다.

질문 2
README 의 Scenario 중
```
"매출 내역"에서는 피자 주문량과 매출을 확인할 수 있어야 하고, "회원 조회" 메뉴에서는 사용자 목록을 확인하고 권한을 설정이 가능해야 합니다.
```
라는 문구가 있어서 추가한 내용입니다.

**Comment by sikutisa** [comment]
history log는 orderer가 아닌, 피자가게 구성원들이 확인할 수 있도록 하는게 맞겠네요. 답변 감사합니다.
