### ISSUE TITLE
간략한 UI에 대한 건의

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#14]
현재 requirement 에 보면 간략한 UI 가 전혀 나와있지 않아
대충 그렸는데, 아직 충분하게 UI들 리스트가 나오지 않은 것 같습니다.
구체적인 내부 UI가 아닌 어떤 UI들이 존재해야하는가에 대해서 같이 그림을 수정해주시면 좋겠습니다.
![2021-04-05 rough ui #01](https://user-images.githubusercontent.com/17357596/113549783-f9497380-962c-11eb-8da4-c1eb489ed854.png)

**Comment by makerdark98** [comment]
그림 수정안하고 무슨 화면 그림이 있어야 될것같다 정도만 말해주셔도 됩니다!

**Comment by sikutisa** [comment]
`| REQ-9-4 | 2 | The system shall change the order status to "invalid" in an emergency. | F |`
Cashier나 Manager에게 status를 invalid로 바꿀 수 있게 하는 옵션이 추가되어야 할 것 같습니다.

**Comment by sikutisa** [comment]
추가적으로, Cashier가 주문을 reject할 수 있는 기능도 포함되어야 할 것 같습니다. 
`| REQ-9 | 2 | The system should allow a cashier to change order's status from "ordered" to ("order accepted" or "order rejected"). | F |`

**Comment by alertjjm** [comment]
![image](https://user-images.githubusercontent.com/46064193/113668477-41c86600-96ed-11eb-8348-99fed0f76103.png)

![image](https://user-images.githubusercontent.com/46064193/113668497-4ab93780-96ed-11eb-8b47-7327b7002a5d.png)

![image](https://user-images.githubusercontent.com/46064193/113668501-4db42800-96ed-11eb-8e18-86749c1e65bc.png)

![image](https://user-images.githubusercontent.com/46064193/113668508-4f7deb80-96ed-11eb-8556-f608cff99bac.png)

**Comment by alertjjm** [comment]
![image](https://user-images.githubusercontent.com/46064193/113669641-0038ba80-96ef-11eb-9ba9-b3926295df6a.png)

**Comment by dkile** [comment]
![KakaoTalk_20210406_165428229](https://user-images.githubusercontent.com/29909393/113677692-d1bfdd00-96f8-11eb-812c-11ffa86837ca.jpg)
