### ISSUE TITLE
4/5 회의록 중 REQ-15 "메뉴페이지에서 카트페이지로 이동할수 있다." 삭제 건의

### ISSUE THREAD

**Issue by identity16** [cau-sw-engineering-2021/online-pizza-ordering-system#15]
4월 5일 회의록의

> [REQ-15] 메뉴페이지에서 카트페이지로 이동할수 있다.

부분에 대해서

> [REQ-2] 모든화면에서 **장바구니**와 (로그인 또는 로그아웃) 버튼이 보여야한다.

부분에 장바구니 버튼을 넣는 것으로 대체한 것으로 기억하는 데

REQ-15를 삭제하는 게 좋을 것 같습니다.
혹시 제가 놓친 남겨야 할 이유가 있다면 알려주셨으면 좋겠습니다.

**Comment by makerdark98** [comment]
삭제하는게 맞는 것 같습니다. 번호는 다른 사람들이 문서화 하는데 영향이 있을수 있으니, 유지하도록 하겠습니다.

감사합니다.
