### ISSUE TITLE
docs/requirements.md에서 기존 Requirements 전부 지우기

### ISSUE THREAD

**Issue by identity16** [cau-sw-engineering-2021/online-pizza-ordering-system#16]
4/5 회의에서 기존 Requirements에 비해 순서/내용 등 많은 내용이 바꼈는데
이것을 docs/requirements.md에 반영하는 과정에서
기존에 있던 항목들과 REQ-#나 내용이 중복되는 경우가 많습니다.

막상 지우려니 다른 분들이 작업한 것을 손대는 상황도 일어날 것 같아
한번 기존 REQ를 다 걸러내야할 필요가 있을 것 같습니다.

**Comment by makerdark98** [comment]
추가적으로 Remove Commit을 남길 필요가 없어서 걸러내지 않은 것인데, 원하신다면 걸러내셔도 큰 영향은 없을 것 같습니다. 
편하신대로 해주시고 이슈 닫아주시면 될 것 같습니다.

감사합니다.

**Comment by identity16** [comment]
그러면 한번 정리하고 커밋하겠습니다!

**Comment by identity16** [comment]
커밋했습니다. 커밋 메시지에 이슈번호 넣는걸 깜빡해서 수동으로 닫습니다ㅎㅎ
