### ISSUE TITLE
[REQ-2, 4] Functional or Not?

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#17]
2번과 4번 항목은 Non Functional 이 아닌가 싶어 질문 드립니다.
Non-functional requirement의 정의를 찾아보면 위키피디아에
```
In systems engineering and requirements engineering, a non-functional requirement (NFR) is a requirement that specifies criteria that can be used to judge the operation of a system, rather than specific behaviors. 
```
다음과 같이 나옵니다.
특정 동작이 아닌 시스템에서 판단하는 것을 말하는데,
메뉴의 아이템마다 보여야하는 기본적인 정보같은 경우 Software 개발을 의뢰하는 Client가 Software Engineer 에게 요청하여 생긴 요구사항으로 보입니다.
따라서 이와 같은 경우 Functional Requirement가 되어야 하는게 아닌지 질문 드립니다.

감사합니다.

**Comment by identity16** [comment]
제가 아직 F, NF의 개념에 혼동이 와서 판단 기준이 제대로 서지 않는 상태입니다.
당장은 이슈 유지한 채로 다른 분들과 함께 더 토론을 한 다음에 결정해보는 건 어떨까요?

**Comment by alertjjm** [comment]
[From pdf 자료]
REQ4 (FR / 3): The system shall show the menu, which select level of game (1~4 level) after selecting “Start”, and then allow player can select level of game using their keyboard and start playing game.

이걸 보면 저는 FR이라고 생각하긴 합니다. 'Non functional requirements (or quality requirements)'라고 나온부분을 보면 저렇게 주요하게 뭘 보여줘야한다는 것은 FR이고,
피자리스트를 보여주긴하는데, Grid 형식으로 보여줘라! [From pdf 자료]
REQ4 (FR / 3): The system shall show the menu, which select level of game (1~4 level) after selecting “Start”, and then allow player can select level of game using their keyboard and start playing game.

이걸 보면 저는 FR이라고 생각하긴 합니다. 'Non functional requirements (or quality requirements)'라고 나온부분을 보면 저렇게 주요하게 뭘 보여줘야한다는 것은 FR이고,
피자리스트를 보여주긴하는데, Grid 형식으로 보여줘라! 아니면, 피자리스트보여주는(main, FR)건 보여주는건데, 거기에다가 원산지까지 더보여주면 더 좋을거같다(sub) 하는것들이 NF라고 생각합니다.

**Comment by identity16** [comment]
그러면 REQ-2, 4 모두 Functional으로 변경하겠습니다.
의견 감사합니다!
