### ISSUE TITLE
[REQ-14] 다른 번역 제안

### ISSUE THREAD

**Issue by identity16** [cau-sw-engineering-2021/online-pizza-ordering-system#18]
REQ-14의 회의록에 나온 원문은 아래와 같습니다.

> 카트페이지에서 메뉴페이지로 이동할수 있다.

지금은 이 문장이 그대로 번역된 상태인데,
이 표현이 조금 모호한 것 같아서

_"카트 페이지에서 카트에 담겨있는 항목의 개별 메뉴 페이지로 이동할 수 있다."_ 정도로 구체화시켜서

**The system should allow an orderer to go to individual menu page of an item in the cart page.**
로 바꾸면 어떨까 제안드립니다.

**Comment by jooomOut** [comment]
앗 좋습니당
