### ISSUE TITLE
[REQ-32], [REQ-33], [REQ-38]삭제 건의

### ISSUE THREAD

**Issue by dkile** [cau-sw-engineering-2021/online-pizza-ordering-system#19]
| REQ-32 | TODO | menu management 에서는 현재 존재하는 피자의 리스트를 보여줘야한다.(req-35와 겹침) | |
| REQ-33 | TODO | 현재 존재하는 모든 유저의 리스트를 보여줘야 한다.(req-37과 겹침) | |

| REQ-35 | 3 | The system shall allow viewing, adding, editing, deleting pizza menus on "menu management" | F |
| REQ-37 | 3 | The system shall allow viewing, adding, editing, deleting members on "member management". | F |

| REQ-38 | TODO | 인증된 사용자는 manager 화면에서만 생성가능하다(member management/ADD 역할 그 자체이고 orderer 회원가입 페이지에 권한 항목이 없기 때문에 당연하게 따라오는거라 생각됩니다.) | NF |

**Comment by alertjjm** [comment]
중복되는게아닌게 어제 회의때 기능적측면이아니라 각각의 메뉴를 클릭했을때 어떤 화면이 나오는지 얘기하는것으로 해서 추가했던거같습니다

**Comment by alertjjm** [comment]
그리고 req38에서도 그냥 add user가아니라 이런경우에만 생성가능하다라고 조건을 달아주는거라 nf로 가능하다생각합니다

**Comment by alertjjm** [comment]
용준님과 얘기되었습니다. 어제 회의때 내용 말씀드렸고 수정or삭제 없이 그대로 가는거로 얘기되었습니다~
