### ISSUE TITLE
commit msg [ADD REQ-8, REQ-9] 피드백

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#2]
REQ-8은 강의자료에 있는거랑 똑같은거기도하고, 일단 저희 시스템에서는 safe home access랑 다르게 history log를 남길 이유가 없고, order log는 주문을 하면 자동으로 항상 남기 때문에 REQ-8은 빼는게 좋을것 같습니다
REQ-9는 타당한 Requirement 같은데 중요한(꼭 구현해야하는) 내용은 아니기 때문에 shall 대신 should로 바꾸는 것은 어떤가요?

**Comment by identity16** [comment]
REQ-8에 대한 내용은 동의합니다.
REQ-9는 Problem Domain의 관점에서 생각했을 때 알레르기 정보 표시가 의무화되어있다고 알고 있기 때문에 shall로 남기는 것이 더 좋다고 생각합니다.

**Comment by alertjjm** [comment]
넵 이해했습니다! 그러면 REQ-9는 그대로 두고 REQ-8은 삭제해주시면 될것 같습니다!

**Comment by identity16** [comment]
네! 커밋하고 이슈 닫겠습니다. 피드백 감사합니다~
