### ISSUE TITLE
NF/F 전체적 수정 및 통일

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#20]
![image](https://user-images.githubusercontent.com/46064193/113822131-05ae0780-97b8-11eb-9e80-1b0340c7012f.png)
출처: https://www.altexsoft.com/blog/non-functional-requirements/

수업 pdf자료에 구체적으로 나와있지않아서 구글링으로 찾아보니 위와 같았습니다.
Performance and scalability: 얼마나 시스템이 빠르게, 얼마나 스트레스를 버틸수있는지?
Portability and compatibility: 버전, 환경 관련 - 저희 req엔 configuration 파일 같은문제가 해당될거같습니다
Reliability, availability, maintainability: 어떻게 failure이나 다운타임에 대응하느냐? -> 저희 req에선 필수정보가 없을  시 shutdown하는 것
Security: 보안, 디도스에 버틸수 있다, CSRF 대응을 할수있다, 시큐어코딩을 한다 등등
Localization: ..?
Usability: 얼마나 사용자가 사용하기 쉬운지(인터페이스 보자마자 바로 사용가능해야한다, 디자인을 보고 얼마나 만족스럽느냐)

이런 내용들이 NF에 해당된다고 하였습니다. 

그런데 제가 저 글을 보고 req를 다시한번 쓱 봤을때 저희 회의때 F인것들을 NF로 한 것들이 많은 것 같습니다..! 위 글이나 수업자료대로라면 NF는 사실 몇개 안나오는게 맞다고 생각합니다
그래서 다른이슈에서도 제가 얘기를 남겼지만, 지금 저희 REQ에서 NF로 되어 있는 것들 중에 Display pizza menus on the first page나, 어떤 버튼이 있어야하고, 비밀번호 재발급을 할수 있어야하고, 어떤 버튼이 있어야하고, Order Id를 줘야되고 이런 내용들은 F라고 생각하고 사실상 NF는 몇개 안나와야된다고 생각합니다. 그래서 지금 NF로 되어 있는 것들중에 F로 바뀔만한 것들을 바꿨으면 좋겠는데 의견을 말씀해주시거나 NF들 중에 F로 바뀔만한 것들을 댓글로 달아주시면 취합 후 한번에 반영하겠습니다! 저 위에 출처 부분이 설명이 아주 잘되어있어서 꼭 한번 읽어보시고 댓글 부탁드립니다

아래에는 의견과 상관없이 NF로 할당된 req들을 전부 리스팅한 것입니다 여기서 보고 이건 F인거 같다 하는것들을 댓글로 적어주시면 될거같습니다
| Identifier | Priority | Requirement | Function/Non-Function |
| - | - | - | - |
| REQ-1 | 1 | The system should show menus of pizzas in the first page | NF |
| REQ-3 | 1 | The system should display "go to cart", "login"/"logout" buttons on every pages | NF |
| REQ-13 | 1 | The system should ask if an orderer wants to go to cart page. | NF |
| REQ-14 | 3 | The system should allow an orderer to go to individual menu page of an item in the cart page. | NF |
| REQ-15 | 3 | The system should allow an orderer to move from the menu page to the shopping cart page. | NF |
| REQ-16 | 3 | The system should allow an orderer to move to order decision phase only from shopping cart page. | NF |
| REQ-17 | 2 | The system should alert a notification saying, "If you are not logged in, you will proceed as a non-member.", before entering the order decision stage.| NF |
| REQ-18 | 1 | The system maintains the contents of the cart that added when he or she is not a member, even if the user logs in| NF |
| REQ-19 | 2 | The system should give an Order ID to the orderer when ordering is completed. | NF |
| REQ-21 | 5 | The system shall not accept orders outside of the opening hours | NF |
| REQ-23 | 1 | The system should take address from stored user information in DB during the order decision phase, if orderer is logged in | NF |
| REQ-27 | 4 | The system should shows all items in the cart. | NF |
| REQ-28| 3 | The System should allow an orderer to move to the order decision stage only if there is more than one in orderer's cart. | NF |
| REQ-32 | 2 | The system shall display total menu list first on "menu management". | NF |
| REQ-33 | 2 | The system shall display total member list first on "member management". | NF |
| REQ-38 | 2 | The system shall allow adding privileged-member only on "member management. | NF |
| REQ-45 | 2 | The system shall allow users to be granted only when they have appropriate authorities. | NF |
| REQ-47 | 3 | The system should get Manager id and password from configuration file. | NF |
| REQ-48 | 1 | The system should maintain only one managmer account. | NF |
| REQ-49 | 2 | The system shall maintain a history log of all orders. | NF |
| REQ-50 | 3 | The system shall be shut down if essential information is absent before starting the system. | NF |
| REQ-51 | 3 | The system should restrict to create orderer account via signup. | NF |
| REQ-52 | 4 | The system shall allow an orderer to order new pizza both as a member or non-member. | NF |
| REQ-59 | 1 | The system should record the last time when order's status has changed. | NF |
| REQ-61 | 5 | The system shall deny the access to user's info when the user logs out. | NF |
| REQ-62 | 3 | The system should check that the password length is more than 8 characters. | NF |
| REQ-63 | 2 | The system should check that the password contains at least one number, upper/lower case and special character. | NF |
| REQ-64 | 5 | The system should maintain an unique user's ID and email. | NF |
| REQ-66 | 1 | The system should get the password when the user try to enter user info page. | NF |
| REQ-67 | 4 | The system should allow password mistakes up to 5 times. | NF |
| REQ-68 | 4 | The system shall encrypt and store orderer pw. | NF |
| REQ-69 | 2 | The system should provide the page that "ordered completed" and "cook completed" can't rewrite(Readonly). | NF |

**Comment by alertjjm** [comment]
저는 req16, req17, req18, req21, req28 req38, req45, req47, req48, req49, req50, req51, req52, req59, req61, req62, req63, req64, req67, req68, req69 를 제외하고는 전부 F로 가야한다고 생각합니다

-- 수정(req654 ->req64)/ 사유: typo --
-- 수정(req28 NF에 추가)/ 사유: 김준기님 의견 --

**Comment by makerdark98** [comment]
양이 조금 많아서 읽어보고 문제가 있다면 오늘 저녁 8시 이전에 코멘트 추가로 달겠습니다
많은 내용 먼저 검토하고 수정해주셔서 감사합니다

**Comment by identity16** [comment]
REQ-15는 [#15] 이슈에서 지우기로 했던 것이기 때문에 다들 판단하실 때 패스하셔도 될 것 같습니다.
requirements.md에서는 제가 지우겠습니다.

**Comment by sikutisa** [comment]
> 저는 req16, req17, req18, req21, req38, req45, req47, req48, req49, req50, req51, req52, req59, req61, req62, req63, req654, req67, req68, req69 를 제외하고는 전부 F로 가야한다고 생각합니다

일단 제가 담당한 ownership에 있는 REQ들 먼저 검토를 했는데. REQ-66의 경우 F로 볼 수 있다고 생각합니다. 다만 REQ-64를 F로 판단하신 이유에 대해 여쭤봐도 될까요? 
REQ-654는 REQ-64의 오타이고, REQ-60은 F인데 표에 실수로 포함됐다고 판단했는데, 다른 의미였다면 알려주시면 감사하겠습니다.

**Comment by jooomOut** [comment]
--생각의 변화로 수정중--

--아닌거 같아서 삭제--

**Comment by alertjjm** [comment]
> > 저는 req16, req17, req18, req21, req38, req45, req47, req48, req49, req50, req51, req52, req59, req61, req62, req63, req654, req67, req68, req69 를 제외하고는 전부 F로 가야한다고 생각합니다
> 
> 일단 제가 담당한 ownership에 있는 REQ들 먼저 검토를 했는데. REQ-66의 경우 F로 볼 수 있다고 생각합니다. 다만 REQ-64를 F로 판단하신 이유에 대해 여쭤봐도 될까요?
> REQ-654는 REQ-64의 오타이고, REQ-60은 F인데 표에 실수로 포함됐다고 판단했는데, 다른 의미였다면 알려주시면 감사하겠습니다.

제 의미는 저기 리스트에 있는 것들 대부분이 F로 가야한다고 생각해서 저기 리스트 중에서 NF라고 생각되는것들만 남겨놨습니다
- REQ66: 저 역시 REQ66은 F라고생각해서 제가 언급하지 않았습니다. 
- REQ654: REQ64의 오타 입니다 감사합니다.
- REQ60: 실수로 표에 포함했습니다 감사합니다.

**Comment by sikutisa** [comment]
> 제 의미는 저기 리스트에 있는 것들 대부분이 F로 가야한다고 생각해서 저기 리스트 중에서 NF라고 생각되는것들만 남겨놨습니다

제가 잘못 이해했었네요. 피드백 감사합니다.

**Comment by alertjjm** [comment]
> 일단 저희 파트인 1-28에서 3번과 23번은 NF 라고 생각합니다. 나머지는 종민님 의견에 동의하구요
> 3번과 23번은 전적으로 유저편의성에 초점을 둔 요구사항, 즉 없어도 아무 상관 없고 있으면 유저에게 편한 부가서비스라고 봅니다.
> 재확인 - <REQ-3, REQ-23>

혹시 저 출처 링크 한번 보셨나욥..? 저도 회의할때 부가기능과 주기능으로 NF와 F를 분류해서 의견을 냈었는데 계속 찜찜해서 구글에 검색을 좀 해봤습니다. 주기능과 부가기능의 문제가 아니라 기능적인것과 아얘 관련이 없는 것이 NFR이었습니다

https://m.blog.naver.com/PostView.nhn?blogId=crowdark7&logNo=104688917&proxyReferer=https:%2F%2Fwww.google.com%2F 

이거도 한번 확인부탁드립니다

**Comment by alertjjm** [comment]
> 저는 req16, req17, req18, req21, req38, req45, req47, req48, req49, req50, req51, req52, req59, req61, req62, req63, req654, req67, req68, req69 를 제외하고는 전부 F로 가야한다고 생각합니다

[추가 언급] 여기에 적어놓은 req들은 제가 NF라고 생각한 것들이고, 여기에 적히지 않은 것들은 전부  F라고 생각했습니당

**Comment by jooomOut** [comment]
> > 일단 저희 파트인 1-28에서 3번과 23번은 NF 라고 생각합니다. 나머지는 종민님 의견에 동의하구요
> > 3번과 23번은 전적으로 유저편의성에 초점을 둔 요구사항, 즉 없어도 아무 상관 없고 있으면 유저에게 편한 부가서비스라고 봅니다.
> > 재확인 - <REQ-3, REQ-23>
> 
> 혹시 저 출처 링크 한번 보셨나욥..? 저도 회의할때 부가기능과 주기능으로 NF와 F를 분류해서 의견을 냈었는데 계속 찜찜해서 구글에 검색을 좀 해봤습니다. 주기능과 부가기능의 문제가 아니라 기능적인것과 아얘 관련이 없는 것이 NFR이었습니다
> 
> https://m.blog.naver.com/PostView.nhn?blogId=crowdark7&logNo=104688917&proxyReferer=https:%2F%2Fwww.google.com%2F
> 
> 이거도 한번 확인부탁드립니다

아 혼자 생각하다가 아닌거같아서 지웠읍니다.

**Comment by jooomOut** [comment]
28번은 NF 아닐까요? 제가 보기엔 시스템의 신뢰성 문제인데, 표현이 단계를 넘어 갈 수 없다~ 이런 식으로 되어 있어서 그렇지 "아무것도 포함하지 않은 주문을 할 수 없다" 와 같은 이야기로보입니다.

**Comment by alertjjm** [comment]
> 28번은 NF 아닐까요? 제가 보기엔 시스템의 신뢰성 문제인데, 표현이 단계를 넘어 갈 수 없다~ 이런 식으로 되어 있어서 그렇지 "아무것도 포함하지 않은 주문을 할 수 없다" 와 같은 이야기로보입니다.

동의합니다 못보고 넘어갔었네요 감사합니다 제가 위에 적었던 댓글에 추가하겠습니다
