### ISSUE TITLE
[Pizza Order] UC5 "extends(delivery option)" 삭제 제안

### ISSUE THREAD

**Issue by identity16** [cau-sw-engineering-2021/online-pizza-ordering-system#21]
개념이 확실하진 않지만 extend/include가 전부 UseCase를 대상으로 하는 것으로 되어있어서,

> UC5 : Order - extends(delivery option)

UC5의 delivery option은 UC가 아니라 항목이 분기되는 부분이기 때문에
extend를 빼고 Flow 작성할 때만 분기하면 어떨까 제안드립니다.

**Comment by jooomOut** [comment]
아 그러네요  딱히 UC로 구분지을게 아니긴 해요 extend 빼는거 동의합니다.

**Comment by alertjjm** [comment]
[다른팀] 넵 저 지금 보고왔는데 usecase는 가능하면 덩이덩이로 추상화된 개념으로 적는게 나을거같네요

**Comment by identity16** [comment]
그러면 빼도록 하겠습니다!
의견 감사합니다~
