### ISSUE TITLE
REQ-23 질문

### ISSUE THREAD

**Issue by dkile** [cau-sw-engineering-2021/online-pizza-ordering-system#22]
REQ-23 : The system should take address from stored user information in DB during the order decision phase, if orderer is logged in.

 1. requirements gathering 단계에서 db같은 구체적인 용어를 써도 되나요?
 2. 주문 결정 단계에 DB에서 주소를 가져오는 것은 어떤 기능을 제공하기 위함인가요?
 
 만약 db 같은 용어를 쓰지 않는 것이 좋다면 이 req가 추적하는 기능을 req로 작성하는 것이 좋다고 생각합니다. db에서 정보를 가져오는건 use case에서 작성하면 되니까요.
 ex) 주문자가 주소를 입력할 때 로그인을 한 유저는 주소를 자동으로 기입한다가 목적이라면 "시스템은 로그인한 유저에 한해서 주문 결정 단계에 주소 입력창을 자동으로 기입한다."
 
db란 용어를 써도 괜찮다면 그냥 req-23의 목적만 req로 추가하면 될 것 같습니다.

**Comment by alertjjm** [comment]
1. 이 부분에 대해선 저는 보류하겠습니다..DB로 그냥 적어도 상관없을지 persistent storage로 추상화해서 적는것이 나을지 정말 잘 모르겠어서..
2. 주문자가 로그인 되어 있을 때 주문을 하려고하면 회원정보에 저장되어 있는 정보들(이름, 주소, 수신자 번호 , ...)를 자동으로 채워준다는 의미입니다.

**Comment by jooomOut** [comment]
1. 저도 일단 적어본거라서 가능할지 아닐지는 모르겠지만 말씀해주신거처럼 그냥 "자동으로 기입한다" 로 적어도 좋을거같네요!
2. 종민님이 설명해주셨읍니다.
