### ISSUE TITLE
Requirements 보충 수정 필요

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#23]
0409회의때 논의되었던 
16 -> 15F 와 16NF 로 쪼갠다. (기능, 제한)
18 -> 원준님의 의견을 지지 (아마도 F)
에 대해 "피자주문" subgroup에서 해당 내용 수정 부탁드립니다!

**Comment by jooomOut** [comment]
확인했습니다
