### ISSUE TITLE
subgroup별 디렉토리 생성해서 파일 이동 건의

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#24]
![image](https://user-images.githubusercontent.com/46064193/114264976-131df880-9a29-11eb-8b48-ecc1b9cc3414.png)

현재 docs밑에 [subgroup]usecase.md 로 되어있는데
domain model도 작업공간이 깃헙에 필요할거같아서 
docs밑에 디렉토리 subgroup name별로 만들어서 작업공간으로 활용하는거 어떻게 생각하세요?

**Comment by sikutisa** [comment]
좋은 생각인 것 같습니다.

**Comment by dkile** [comment]
저도 찬성합니다

**Comment by jooomOut** [comment]
찬성합니다.
