### ISSUE TITLE
Domain model tracability Matrix

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#33]
통합문서에 Domain Model Tracability Matrix를 추가해주세요.
모든 서브그룹이 해야하는 만큼, 본인 서브그룹이 완료되었다면
서브그룹 A 추가 완료했습니다.
와 같이 댓글을 작성해주세요.

**Comment by sikutisa** [comment]
서브그룹C 추가 완료했습니다.

**Comment by alertjjm** [comment]
subgroup B done
