### ISSUE TITLE
Subteam C Domain model 파일 업로드

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#34]
합쳐서 올려놓긴했는데 그래도 각자 sub team문서는 올라와있는게 좋을거같아서
![image](https://user-images.githubusercontent.com/46064193/115982560-15f71c80-a5d7-11eb-97a3-ff1be8be4986.png)

여기에 혹시 문서 있으시면 하나 올려주세요~

**Comment by sikutisa** [comment]
업로드 완료 했습니다.
