### ISSUE TITLE
ERD 확인

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#35]
각자 자기 subteam관련된 테이블 확인하시고 칼럼빠진거나 참조관계 잘못된거나 칼럼이름 바뀌었으면 하는거 말해주세요! 문제없으시면 댓글로 "Subteam xx 확인" 써주세여. 1차로 만들어본거니까 자유롭게 의견주시고 5월 15일 아침부터 일단 이거 Vo로 만들어보려니까 그 전까지 확인부탁드립니다

![pizzaordering](https://user-images.githubusercontent.com/46064193/118231871-a768f880-b4ca-11eb-8f93-8881baf45a0c.png)

**Comment by alertjjm** [comment]
Subteam B 확인

**Comment by sikutisa** [comment]
Subteam C 확인했습니다.

**Comment by identity16** [comment]
Subteam A의 경우, 장바구니에 해당하는 관계가 표현되지 않은 것 같습니다!

Class Diagram에서 어떻게 표현해야될지 모르겠는데,
User - Item의 Relationship을 나타내는 테이블이 필요해 보입니다!
(제가 ERD를 제대로 작성한 적이 없어서 더 나은 형태가 있다면 정정 부탁드려요)
아래와 같은 형태면 되지 않을까 생각합니다.

[cart]
FK user_id
FK item_id

**Comment by alertjjm** [comment]
![pizzaordering (2)](https://user-images.githubusercontent.com/46064193/118279901-9b9b2780-b506-11eb-8543-4f1191542b72.png)

@identity16 @sikutisa @makerdark98 @dkile @jooomOut 
수정한 ERD인데 확인해보시고 각자 의견 부탁드립니당~

**Comment by alertjjm** [comment]
제가 올린 코멘트이니 당연히!
저는 확인했습니다!

**Comment by identity16** [comment]
확인했습니다! 제 눈에는 더이상 문제가 보이지 않습니다..
