### ISSUE TITLE
class diagram , object sequence diagram png파일

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#36]
class diagram , object sequence diagram png파일 각각
https://github.com/cau-sw-engineering-2021/online-pizza-ordering-system/tree/master/docs/The2ndCheckpointOutput 
여기에 모두 다 올려주세요~ 
완료된 subteam은  comment로 알려주세요

**Comment by alertjjm** [comment]
Subteam B done

**Comment by sikutisa** [comment]
Subteam C done
