### ISSUE TITLE
추가 요구사항 건의

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#4]
지금 피자 토핑과 같은 것들은 명시되어있는데,
반드시 피자메뉴에 포함되어야하는 것들(가격, 피자 명칭, 사이즈 등)에 대한 명시가 없는데 이를 추가해야된다고 생각합니다.
혹시 위와 같은게 모두 옵션으로 취급하는 것인지가 궁금합니다.

**Comment by alertjjm** [comment]
가격, 피자 명칭, 사이즈 등은 show menu에 해당이 된다고 생각합니다. 부연설명을 해당 REQ에 이어서 한번에 작성하겠습니다.
