### ISSUE TITLE
rest api document

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#40]
front 와 backend가 서로 통신할때 필요한 rest api 정의 및 dummy 데이터 생성

**Comment by alertjjm** [comment]
1) 여기서부터는 각자 subteam들끼리 정의하고 개발하는것 어떤가요? 엔진이랑 루트만 공유하고 subteam별로 패키지별로 나눠서 개발하니까요
2) 그리고 REST Api 아니고 그냥 api 맞죠..?ㅋㅋ여기서는 restful 지키는거보다 그냥 데이터 규격에 맞게 잘 던져지나를 보면되지않을까해서요

**Comment by makerdark98** [comment]
front end 쪽에서는 만약 data가 string이라면, error 코드인지 data인지 구별하기 어려워서 json 방식 + HTTP status code로 그걸 알려줘야지 판단할수 있다고 생각합니다. 지금 샘플코드 작업중이라 아마도 큰 지장없이 다들 interface 직관적으로 이해할수 있게 코드 제공될것 같습니다.

**Comment by alertjjm** [comment]
아하 그정도의 rest api면 저도 좋습니다 authcontroller도 민욱님께서 말씀해주신대로 response entity로 구현해놨습니다

저는 로이필딩 rest api 원칙 다 지키고 하자는줄알고 드린 말씀이었는데 민욱님말씀해주신 정도면 동의합니다!
