### ISSUE TITLE
[에러] SQL수정

### ISSUE THREAD

**Issue by alertjjm** [cau-sw-engineering-2021/online-pizza-ordering-system#42]
개발하다보니 제가 SQL에 password를 빼먹은점, 예약어 keyword를 사용한점(order)때문에
Table 수정을 두 부분 했습니다.
PR날린거 jwt 정상 작동하는데 테스트환경 DB와 달라서 DB conneciton fail난것 같은데 확인부탁드립니다
아래에 새로운 sql문 첨부합니다.

[pizzaorder.zip](https://github.com/cau-sw-engineering-2021/online-pizza-ordering-system/files/6496054/pizzaorder.zip)

**Comment by makerdark98** [comment]
이미 메신저를 통해서 application properties 설정 문제였고 이후 commit 을 통해서 해결된 이슈이니 닫겠습니다.

**Comment by makerdark98** [comment]
![image](https://user-images.githubusercontent.com/17357596/118844408-e6051580-b905-11eb-9009-b052e398cb6d.png)

hibernate 설정을 잘못 알고 있어
create-drop 이 기본 옵션인줄 알고있었습니다.
직접 sql 실행해줘야 해서 이야기 진행하고 서버에 sql 처리 완료했습니다.
