### ISSUE TITLE
서버 접속 방법 및 배포 설정 안내

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#45]
* 배포 github action에서 자동 실행 부분은 제거되었고, 현재는 build 만 체크합니다.
* 실제 서버에 자동 실행되는 스크립트 실행방법 안내 문서 만들어야합니다.
* 배포 context path 전파 (반드시 /pizza로 시작해야만 하는 거 전파)

* 서버 ssh 계정정보 전파 및 리소스 확인
* mysql over ssh 설정 다시 확인 (heidisql 에서 에러 발생 on alertjjm)

**Comment by alertjjm** [comment]
질문) 세번째 것 의문이 들어 질문드립니다. localhost:8080/managemnt/adduser, localhost:8080/management/addpizza 이런식이 아니라,
 localhost:8080/**pizza**/managemnt/adduser, localhost:8080/**pizza**/management/addpizza 이런식으로 /pizza 밑에서 시작해야한다는 뜻이죠?

**Comment by makerdark98** [comment]
네 지금 배포서버는 그렇게 설정을 해놨는데, 불편하면 aws로 할까요?
시연을 직접하지 않고 동영상으로 대체해도 된다고해서 그냥 다들 로컬로 돌려도 되나 싶기도 하네요.

**Comment by alertjjm** [comment]
아 로컬로돌려도될거같긴하네요.
제 의도는 그냥 확실하게 하고 가려고 확인차 여쭤봤던거예요!
