### ISSUE TITLE
Some requirements are too ambiguous.

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#6]
`The system should allow xxx to xxx` is a too ambiguous sentence for the requirement document.
It is user-story style. Decorating the sentence does not mean IEEE-830 style requirement document.
We need to change some requirements.

문장 표현에서 강조기호가 독성말투라고 생각해서 수정했습니다.
거친 표현 사용해서 죄송합니다.

**Comment by makerdark98** [comment]
제 생각에는 
`The system should provide pages to (verb)`
의 형태는 어떨까 싶습니다.
토론하고자 연 issue이니 의견 나누고 정립되면 닫으면 좋겠습니다.

**Comment by alertjjm** [comment]
![image](https://user-images.githubusercontent.com/46064193/113478086-8a9bd700-94c1-11eb-807a-feddc3fc70ce.png)
 
The system should allow xxx to xxx style도 ieee830에서 많이 쓰는 스타일인거같습니다

**Comment by makerdark98** [comment]
![image](https://user-images.githubusercontent.com/17357596/113478136-dfd7e880-94c1-11eb-9899-580d57431ee9.png)
제가 본 자료는 이건데, 조금 상반된 내용인 것 같은데 allow의 형식으로 가면 모호한 측면이 있다고 생각합니다.

정확히 제가 모호하다고 생각하는 부분은 `granted user` 부분인데
```
 The system should allow a casher to change order's status from "ordered" to ("order accepted" or "order rejected
 The system should allow a cook to change order's status from "order accepted" to "cook completed" 
 The system should allow a delivery man and server to change order's status from "cook completed" to ("delivering
 The system should allow a delivery man to change order's status from "delivering" to "delivery complted". 
```
처럼 가는건 어떠신가요?

**Comment by makerdark98** [comment]
추가적으로 etc라는 항목이 요구사항에는 모호하다고 생각합니다.

**Comment by alertjjm** [comment]
granted user 라는 말씀이  allow 다음에 "누구에게"를 명시하자는 말씀이신가요?

**Comment by alertjjm** [comment]
> 추가적으로 etc라는 항목이 요구사항에는 모호하다고 생각합니다.

동의합니다 명확하게 해서 수정하겠습니다

**Comment by makerdark98** [comment]
혹시 이와 관련해서 
https://github.com/makerdark98/online-pizza-ordering-system/blob/master/docs/requirement_gathered.md
한번 읽어봐주실수 있을까요?

**Comment by alertjjm** [comment]
읽고왔습니다! 9-1,9-2,9-3 등에서 해주신 방식 좋은거같습니다!! 중간에 typo 고친 커밋도있어서 컨플릭트안나게 PR해주시면 merge하고 그다음에 나머지부분들도 모호한 표현들 제가 수정해보겠습니다

**Comment by makerdark98** [comment]
감사합니다.
