### ISSUE TITLE
Remove REQ-# temporarily.

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#7]
REQ-#  makes unncessary conflicts in chainging it.
From now on, do not mind REQ-# and do not write on this position until the requirement document is established.

REQ-# 를 수정하면서 무의미하게 코드 수정이 일어나고 있습니다.
지금부터는 모두가 requirement를 동결하기 전까지는 더이상 이 항목에 신경쓰지 말고 작업해주시길 바랍니다(굳이 지우지도, 쓰지도 마시기길 바랍니다).

**Comment by alertjjm** [comment]
넵 확인했습니다

**Comment by sikutisa** [comment]
확인했습니다

**Comment by dkile** [comment]
확인했습니다

**Comment by makerdark98** [comment]
모두 확인했다고 판단하면 내일(4월 4일) 중으로 이슈 닫겠습니다.

**Comment by jooomOut** [comment]
확인했어요

**Comment by identity16** [comment]
확인했습니다
